// Generated by https://quicktype.io

export interface AuthenticationListModel {
  data: AuthenticationData[];
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface AuthenticationData {
  id: string;
  agt: string;
  acct: string;
  gr: string;
  privi: number;
  topIds: string;
  ts: number;
  du: number;
  sigD: SigD;
  h: string;
  eH: string;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: null;
}

export interface SigD {
  ty: string;
  pubK: string;
  sig: string;
}
