// Generated by https://quicktype.io

export interface BlockStatsListModel {
  data: BlockStat[];
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface BlockStat {
  id: string;
  blk: number;
  t: number;
  ec: number;
  mc: number;
  tc: number;
  ac: number;
  c: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: null;
}
