// Generated by https://quicktype.io

export interface MessageListModel {
  data: MessageData[];
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface MessageData {
  id: string;
  topId: string;
  s: string;
  r: string;
  d: string;
  a: A[];
  e: E;
  h: string;
  atts: Att[];
  sig: string;
  agt: string;
  dH: string;
  url: string;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string;
}

export interface A {
  c: string;
  abi: string;
  a: string;
  pa: string[];
}

export interface Att {
  cid: string;
  h: string;
}

export interface E {
  mod: string;
  h: string;
  val: string;
}
