// Generated by https://quicktype.io

import { Entities } from '@mlayerprotocol/core';

export interface TopicListModel {
  data: TopicData[];
  _meta?: Meta;
}

export interface Meta {
  version: string;
}

export interface TopicData {
  id: string;
  ref: string;
  n: string;
  hand: string;
  desc: string;
  snet: string;
  agt: string;
  meta: string;
  acct: string;
  pub: boolean;
  eH: string;
  h: string;
  bal: number;
  dSubRol: Entities.SubscriberRole;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: null;
}
