// Generated by https://quicktype.io

export interface TopicListModel {
  data: TopicData[];
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface TopicData {
  id: string;
  ref: string;
  n: string;
  hand: string;
  desc: string;
  agt: string;
  pub: boolean;
  eH: string;
  h: string;
  bal: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: null;
}
