// Generated by https://quicktype.io

export interface MainStatsModel {
  data: MainData;
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface MainData {
  accounts: number | bigint;
  topic_balance: number | bigint;
  messages: number | bigint;
  message_cost: number | bigint;
}
