// Generated by https://quicktype.io

export interface MainStatsModel {
  data: MainData;
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface MainData {
  accounts: number;
  topic_balance: number;
  messages: number;
  message_cost: number;
}
